### ISSUE TITLE
Fix no gallery page

### ISSUE THREAD

**Issue by ametisf** [ametisf/chronicles#24]
- if gallery given name doesn't match any gallery, server fails
```
/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property '_id' of null
    at Promise.<anonymous> (/home/frantisek/Node/Chronicles/routes/backend/page.js:38:33)
    at Promise.<anonymous> (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mpromise/lib/promise.js:178:8)
    at Promise.emit (events.js:129:20)
    at Promise.emit (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mpromise/lib/promise.js:126:15)
    at /home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
    at /home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/cursor.js:778:35
    at Cursor.close (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
    at Cursor.nextObject (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/cursor.js:778:17)
```

**Comment by ametisf** [comment]
- done
- but when you edit page without gallery, server fails too
```
/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property 'image' of null
    at Promise.<anonymous> (/home/frantisek/Node/Chronicles/routes/backend/page.js:62:44)
    at Promise.<anonymous> (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mpromise/lib/promise.js:178:8)
    at Promise.emit (events.js:129:20)
    at Promise.emit (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mpromise/lib/promise.js:126:15)
    at /home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
    at /home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/cursor.js:778:35
    at Cursor.close (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
    at Cursor.nextObject (/home/frantisek/Node/Chronicles/node_modules/monk/node_modules/mongodb/lib/mongodb/cursor.js:778:17)
```

**Comment by ametisf** [comment]
- done
